### ISSUE TITLE
sudo rosdep init failed

### ISSUE THREAD

**Issue by suiato** [karaage0703/jetson-nano-tools#6]
When running install-ros-melodic.sh, `sudo rosdep init `failed.
As shown in http://wiki.ros.org/Installation/Ubuntu , the following command had to be executed to proceed:
```
$ sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential
```

**Comment by karaage0703** [comment]
@suiato 
Thanks for your comment. And sorry for late reply.
I updated `install-ros-melodic.sh` script. Thanks!

Refer to : https://github.com/ros-infrastructure/rosdep/issues/745
