### ISSUE TITLE
install-pose-estimation-v44.sh TfPoseEstimator/image Error

### ISSUE THREAD

**Issue by lucky2046** [karaage0703/jetson-nano-tools#7]
sudo  bash install-pose-estimation-v44.sh
then
python3 run_jetson_nano.py

Enviroment:
Jetpack 4.4
cuda 10.2
tensorflow 2.2

Error stack:
Exception has occurred: KeyError
"The name 'TfPoseEstimator/image:0' refers to a Tensor which does not exist. The operation, 'TfPoseEstimator/image', does not exist in the graph."
  File "/home/mixislink/tf-pose-estimation/tf_pose/estimator.py", line 338, in __init__
    self.tensor_image = self.graph.get_tensor_by_name('TfPoseEstimator/image:0')
  File "/home/mixislink/tf-pose-estimation/run_jetson_nano.py", line 52, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(432, 368), trt_bool=str2bool(args.tensorrt))

**Comment by karaage0703** [comment]
@luckywuhan 
Sorry for very late reply.
I checked pose estimation

Enviroment:
Jetpack 4.5
tensorflow 1.15.4

I can check pose estimation work.

**Comment by abhi9rocks** [comment]
any update on this i'm facing this error KeyError: "The name 'TfPoseEstimator/image:0' refers to a Tensor which does not exist. The operation, 'TfPoseEstimator/image', does not exist in the graph."

**Comment by siddhipandare** [comment]
@abhi9rocks this solved the error for me --> [Link](https://github.com/gsethi2409/tf-pose-estimation/issues/12#issuecomment-842847372)
